import type { Metadata } from "next";
import axios from "axios";
import UserCard from "@/components/userCard";

export const metadata: Metadata = {
    title: "User",
    description: "Generated by create next app",
};

interface User {
    id: number;
    name: string;
    email: string;
    username: string;
    website: string;
    company: Company;
    address: Address;
}

interface Company {
    name: string;
    bs: string;
    catchPhrase: string;
}

interface Address {
    street: string;
    suite: string;
    city: string;
    zipcode: string;
    geo: Coordinate;
}

interface Coordinate {
    lat: string;
    lang: string;
}

const UserPage = async () => {
    let users: User[] = [];

    const getUser = async () => {
        const res = await axios.get(
            "https://jsonplaceholder.typicode.com/users",
        );
        users = res?.data;
    };

    await getUser();

    return (
        <>
            {users.map((user) => (
                <>
                    <UserCard
                        key={user.id}
                        name={user.name}
                        email={user.email}
                    />
                    {user.id}
                    {user.name}
                    {user.username}
                    {user.email}
                    {user.website}
                    {user.company.name}
                    {user.company.catchPhrase}
                    {user.company.bs}
                    {user.address.street}
                    {user.address.suite}
                    {user.address.city}
                    {user.address.zipcode}
                    {user.address.geo.lat}
                    {user.address.geo.lang}
                </>
            ))}
        </>
    );
};

export default UserPage;
