import type { Metadata } from "next";
import React from "react";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/layout/layoutWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next Appz",
    description: "Generated by create next app",
    icons: { icon: "/assets/favicon.ico" },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AntdRegistry>
                    <LayoutWrapper>{children}</LayoutWrapper>
                </AntdRegistry>
            </body>
        </html>
    );
}
