import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'mdb-react-ui-kit/dist/css/mdb.min.css';
import "@fortawesome/fontawesome-free/css/all.min.css";
import "./globals.css";
import Sidebar from  "@/components/sidebar"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next Appz",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Sidebar />
                {children}
            </body>
        </html>
    );
}
